spring:
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      enabled: true
  datasource:
    url: jdbc:h2:file:/data/demodb;DB_CLOSE_ON_EXIT=TRUE;AUTO_RECONNECT=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true